In [9]:
import matplotlib.pyplot as plt
import pandas as pd


df = pd.read_csv('Dataset/virtual_mouse_data.csv')

df

,lm_0_x,lm_0_y,lm_1_x,lm_1_y,lm_2_x,lm_2_y,lm_3_x,lm_3_y,lm_4_x,lm_4_y,...,lm_16_y,lm_17_x,lm_17_y,lm_18_x,lm_18_y,lm_19_x,lm_19_y,lm_20_x,lm_20_y,gesture_label
0,0,0,-34,-27,-61,-73,-60,-115,-34,-133,...,-56,50,-89,40,-111,22,-83,12,-58,Move
1,0,0,-34,-20,-65,-64,-68,-105,-44,-126,...,-43,54,-89,41,-107,22,-80,8,-57,Move
2,0,0,-37,-27,-64,-71,-65,-105,-40,-119,...,-49,56,-87,47,-107,29,-81,18,-58,Move
3,0,0,-38,-15,-74,-53,-87,-88,-68,-110,...,-46,44,-92,26,-107,10,-81,0,-60,Move
4,0,0,-41,-7,-89,-32,-115,-62,-107,-90,...,-38,16,-106,-18,-107,-29,-77,-30,-54,Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5618,0,0,-33,0,-65,-22,-70,-53,-61,-82,...,-172,-25,-85,-46,-103,-48,-84,-42,-63,Right_Click
5619,0,0,-32,-1,-60,-25,-61,-56,-54,-81,...,-175,-17,-85,-32,-105,-38,-90,-38,-75,Right_Click
5620,0,0,-33,-1,-62,-24,-62,-54,-54,-79,...,-180,-12,-88,-28,-108,-35,-93,-37,-76,Right_Click
5621,0,0,-30,0,-57,-25,-53,-55,-39,-78,...,-181,-4,-79,-19,-102,-26,-85,-26,-66,Right_Click
5622,0,0,-30,-1,-52,-18,-45,-38,-31,-55,...,-173,12,-66,3,-82,-12,-68,-21,-51,Right_Click

In [10]:
df.shape

(5623, 43)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1589 entries, 0 to 1588
Data columns (total 43 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   lm_0_x         1589 non-null   int64
 1   lm_0_y         1589 non-null   int64
 2   lm_1_x         1589 non-null   int64
 3   lm_1_y         1589 non-null   int64
 4   lm_2_x         1589 non-null   int64
 5   lm_2_y         1589 non-null   int64
 6   lm_3_x         1589 non-null   int64
 7   lm_3_y         1589 non-null   int64
 8   lm_4_x         1589 non-null   int64
 9   lm_4_y         1589 non-null   int64
 10  lm_5_x         1589 non-null   int64
 11  lm_5_y         1589 non-null   int64
 12  lm_6_x         1589 non-null   int64
 13  lm_6_y         1589 non-null   int64
 14  lm_7_x         1589 non-null   int64
 15  lm_7_y         1589 non-null   int64
 16  lm_8_x         1589 non-null   int64
 17  lm_8_y         1589 non-null   int64
 18  lm_9_x         1589 non-null   int64
 19  lm_9_y         1589 non-null   int64
 20  lm_10_x        1589 non-null   int64
 21  lm_10_y        1589 non-null   int64
 22  lm_11_x        1589 non-null   int64
 23  lm_11_y        1589 non-null   int64
 24  lm_12_x        1589 non-null   int64
 25  lm_12_y        1589 non-null   int64
 26  lm_13_x        1589 non-null   int64
 27  lm_13_y        1589 non-null   int64
 28  lm_14_x        1589 non-null   int64
 29  lm_14_y        1589 non-null   int64
 30  lm_15_x        1589 non-null   int64
 31  lm_15_y        1589 non-null   int64
 32  lm_16_x        1589 non-null   int64
 33  lm_16_y        1589 non-null   int64
 34  lm_17_x        1589 non-null   int64
 35  lm_17_y        1589 non-null   int64
 36  lm_18_x        1589 non-null   int64
 37  lm_18_y        1589 non-null   int64
 38  lm_19_x        1589 non-null   int64
 39  lm_19_y        1589 non-null   int64
 40  lm_20_x        1589 non-null   int64
 41  lm_20_y        1589 non-null   int64
 42  gesture_label  1589 non-null   str
dtypes: int64(42), str(1)
memory usage: 533.9 KB

In [21]:
df.head()

,landmark_0_x,landmark_0_y,landmark_0_z,landmark_1_x,landmark_1_y,landmark_1_z,landmark_2_x,landmark_2_y,landmark_2_z,landmark_3_x,...,landmark_18_x,landmark_18_y,landmark_18_z,landmark_19_x,landmark_19_y,landmark_19_z,landmark_20_x,landmark_20_y,landmark_20_z,gesture_label
0,0.0,0.0,0.0,-0.212894,-0.118748,-0.089845,-0.366080,-0.409843,-0.125444,-0.421223,...,0.158217,-1.149567,-0.181631,0.192844,-1.342660,-0.211538,0.223450,-1.529465,-0.231995,open
1,0.0,0.0,0.0,-0.205918,-0.169344,-0.067587,-0.342462,-0.496585,-0.095487,-0.391191,...,0.212171,-1.084608,-0.188254,0.234912,-1.273860,-0.215867,0.245300,-1.454941,-0.236057,open
2,0.0,0.0,0.0,-0.210932,-0.119221,-0.100315,-0.360134,-0.402277,-0.138147,-0.407761,...,0.134115,-1.157441,-0.155088,0.166188,-1.347972,-0.187106,0.195030,-1.532315,-0.208959,open
3,0.0,0.0,0.0,-0.195637,-0.205945,-0.072673,-0.318548,-0.536681,-0.102783,-0.351157,...,0.239663,-1.091112,-0.133814,0.253077,-1.275179,-0.157673,0.248480,-1.452760,-0.174308,open
4,0.0,0.0,0.0,-0.209731,-0.162483,-0.095658,-0.341784,-0.495487,-0.134774,-0.389092,...,0.298941,-1.036282,-0.201321,0.358612,-1.196013,-0.233892,0.409928,-1.354282,-0.255904,open

In [3]:
# هذا السطر يجبر مكتبة بانداز على عرض جميع الصفوف بدون اختصار
pd.set_option('display.max_rows', None)
#pd.reset_option('display.max_rows')

df.describe().T

          count        mean         std    min    25%    50%   75%    max
lm_0_x   3263.0    0.000000    0.000000    0.0    0.0    0.0   0.0    0.0
lm_0_y   3263.0    0.000000    0.000000    0.0    0.0    0.0   0.0    0.0
lm_1_x   3263.0  -35.678210   19.645901 -102.0  -47.0  -37.0 -25.0   65.0
lm_1_y   3263.0    0.709163   25.122001  -95.0  -17.0    0.0  19.0   68.0
lm_2_x   3263.0  -70.735519   41.494885 -220.0  -95.0  -74.0 -47.0  113.0
lm_2_y   3263.0  -15.851364   50.136671 -164.0  -48.0  -25.0  22.0  112.0
lm_3_x   3263.0  -87.115231   59.014543 -308.0 -125.0  -96.0 -50.0  127.0
lm_3_y   3263.0  -39.926142   65.771200 -227.0  -89.0  -51.0   8.0  134.0
lm_4_x   3263.0  -87.572173   72.318100 -353.0 -139.0  -95.0 -40.0  113.0
lm_4_y   3263.0  -60.884156   71.788871 -290.0 -113.5  -70.0 -13.0  169.0
lm_5_x   3263.0  -78.815507   61.512629 -275.0 -120.0  -89.0 -47.0  137.0
lm_5_y   3263.0  -53.956175   63.860288 -253.0  -99.0  -61.0 -16.0  120.0
lm_6_x   3263.0 -107.782409   84.666257 -364.0 -165.5 -122.0 -65.0  200.0
lm_6_y   3263.0  -73.083665   90.624988 -366.0 -137.0  -83.0 -18.0  173.0
lm_7_x   3263.0 -120.080601   96.644912 -405.0 -188.0 -136.0 -69.0  244.0
lm_7_y   3263.0  -79.105424  106.803374 -435.0 -156.0  -89.0 -14.0  205.0
lm_8_x   3263.0 -129.160895  108.484624 -456.0 -209.0 -144.0 -68.0  276.0
lm_8_y   3263.0  -85.910512  120.373754 -494.0 -175.0  -94.0 -13.0  230.0
lm_9_x   3263.0  -61.893043   62.745493 -246.0 -109.0  -70.0 -23.0  136.0
lm_9_y   3263.0  -67.433037   57.272947 -267.0 -108.0  -70.0 -36.0   85.0
lm_10_x  3263.0  -86.863010   85.841487 -350.0 -151.0  -99.0 -34.0  150.0
lm_10_y  3263.0  -91.041067   83.770636 -400.0 -151.0  -96.0 -44.0  130.0
lm_11_x  3263.0  -92.323016   91.507418 -352.0 -160.0  -94.0 -38.0  185.0
lm_11_y  3263.0  -89.778731   96.537626 -480.0 -160.0  -87.0 -34.0  158.0
lm_12_x  3263.0  -96.696292  100.876548 -396.0 -172.0  -91.0 -37.0  220.0
lm_12_y  3263.0  -91.924916  109.064320 -551.0 -167.0  -77.0 -28.0  196.0
lm_13_x  3263.0  -41.684952   61.675542 -222.0  -90.0  -44.0   0.0  135.0
lm_13_y  3263.0  -74.069568   49.005040 -250.0 -107.0  -77.0 -43.0   52.0
lm_14_x  3263.0  -62.740116   79.098720 -329.0 -123.5  -67.0  -6.0  155.0
lm_14_y  3263.0  -94.379099   70.251022 -382.0 -143.0  -97.0 -50.0  117.0
lm_15_x  3263.0  -65.948820   78.018443 -341.0 -116.0  -65.0 -13.0  187.0
lm_15_y  3263.0  -84.348759   78.409522 -463.0 -130.0  -77.0 -37.0  150.0
lm_16_x  3263.0  -67.587803   83.231070 -383.0 -114.0  -56.0 -16.0  213.0
lm_16_y  3263.0  -80.706712   88.581284 -533.0 -124.0  -62.0 -30.0  187.0
lm_17_x  3263.0  -19.324548   59.661341 -198.0  -67.0  -16.0  25.0  130.0
lm_17_y  3263.0  -75.587496   41.906515 -226.0 -101.0  -77.0 -47.0   60.0
lm_18_x  3263.0  -37.534477   70.216748 -264.0  -91.5  -38.0  19.0  153.0
lm_18_y  3263.0  -87.656758   56.717062 -312.0 -127.0  -89.0 -49.5  114.0
lm_19_x  3263.0  -40.604658   67.015976 -306.0  -83.0  -40.0   8.0  181.0
lm_19_y  3263.0  -76.578609   62.005146 -379.0 -112.0  -70.0 -38.0  131.0
lm_20_x  3263.0  -40.463684   67.873940 -342.0  -76.0  -34.0   3.0  208.0
lm_20_y  3263.0  -69.594545   68.874388 -446.0  -99.0  -57.0 -30.0  160.0

In [ ]:
print(df['gesture_label'].value_counts())

gesture_label
Move           1280
Drag            949
Scroll          936
Left_Click      881
Right_Click     808
Neutral         769
Name: count, dtype: int64

:

In [2]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt

print("Shape: ",df.shape)
print("Number of rows: ",df.shape[0])
print("Number of columns: ",df.shape[1])

Shape:  (840, 43)
Number of rows:  840
Number of columns:  43

In [3]:
print("Duplicated rows: ",df.duplicated().sum())

#19

Duplicated rows:  0

In [4]:
print(df.isnull().sum()[df.isnull().sum()>0])

Series([], dtype: int64)